"""removed multiple_choice_questions table

Revision ID: abc8116011ed
Revises: e34a286eea43
Create Date: 2023-11-10 19:33:05.272119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc8116011ed'
down_revision = 'e34a286eea43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
